import {
  Activity,
  Anchor,
  Aperture,
  Atom,
  Award,
  Beaker,
  Bell,
  Bird,
  Bitcoin,
  Bookmark,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  ChartBar,
  Check,
  Chrome,
  CircuitBoard,
  Clapperboard,
  Cloud,
  Code,
  Coffee,
  Command,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Diamond,
  Dna,
  Dog,
  DollarSign,
  Droplet,
  Drum,
  Egg,
  Eye,
  Feather,
  Figma,
  FileCode,
  FileText,
  Film,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  FolderClosed,
  FolderGit2,
  FolderInput,
  FolderKanban,
  Footprints,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  Github,
  GitMerge,
  Globe,
  Globe2,
  GraduationCap,
  Hammer,
  HardDrive,
  HardHat,
  Heart,
  Hexagon,
  Hourglass,
  Image,
  Infinity as InfinityIcon,
  Joystick,
  Key,
  Keyboard,
  Lamp,
  Laptop,
  Layers,
  LayoutDashboard,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  Lock,
  LogIn,
  Magnet,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MemoryStick,
  MessageCircle,
  Mic,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Mouse,
  Music,
  Network,
  Newspaper,
  Notebook,
  Package,
  PackageOpen,
  Palette,
  Paperclip,
  Pencil,
  Phone,
  Pin,
  PlaneTakeoff,
  Plug,
  Power,
  Printer,
  Puzzle,
  Radar,
  Radio,
  Rainbow,
  Rocket,
  RotateCcw,
  Rss,
  Save,
  Scale,
  Scissors,
  ScreenShare,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sigma,
  Signal,
  Skull,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Sparkles,
  Speaker,
  Spool,
  Square,
  Star,
  Sun,
  Swords,
  Tag,
  Target,
  Telescope,
  Tent,
  Terminal,
  TerminalSquare,
  ThermometerSun,
  Timer,
  ToyBrick,
  Train,
  TreePine,
  Trello,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Unlock,
  UserRound,
  Users,
  Utensils,
  Video,
  Volume2,
  Wallet,
  Wand2,
  Watch,
  Webhook,
  Wifi,
  Wind,
  Wrench,
  Youtube,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// Note: a couple of names referenced above (e.g. `Thumbnail`, `Spool`,
// `ChartBar`) are aliases that some lucide-react versions only ship under
// alternate names. The catalog filters these out at runtime if undefined,
// so failing to find one in the install just means the icon is skipped.
export const PROJECT_ICON_CATALOG: Record<string, LucideIcon | undefined> = {
  'folder-closed': FolderClosed,
  'folder-input': FolderInput,
  'folder-git': FolderGit2,
  'folder-kanban': FolderKanban,
  code: Code,
  'file-code': FileCode,
  'file-text': FileText,
  terminal: Terminal,
  'terminal-square': TerminalSquare,
  command: Command,
  database: Database,
  layers: Layers,
  box: Box,
  package: Package,
  'package-open': PackageOpen,
  cpu: Cpu,
  'circuit-board': CircuitBoard,
  'memory-stick': MemoryStick,
  'hard-drive': HardDrive,
  monitor: Monitor,
  laptop: Laptop,
  smartphone: Smartphone,
  keyboard: Keyboard,
  mouse: Mouse,
  printer: Printer,
  globe: Globe,
  'globe-2': Globe2,
  network: Network,
  wifi: Wifi,
  signal: Signal,
  rss: Rss,
  webhook: Webhook,
  github: Github,
  'git-branch': GitBranch,
  'git-merge': GitMerge,
  server: Server,
  cloud: Cloud,
  briefcase: Briefcase,
  rocket: Rocket,
  'plane-takeoff': PlaneTakeoff,
  car: Car,
  truck: Truck,
  train: Train,
  star: Star,
  heart: Heart,
  zap: Zap,
  sparkles: Sparkles,
  flame: Flame,
  hammer: Hammer,
  wrench: Wrench,
  brush: Brush,
  pencil: Pencil,
  'wand-2': Wand2,
  scissors: Scissors,
  library: Library,
  bot: Bot,
  brain: Brain,
  beaker: Beaker,
  'flask-conical': FlaskConical,
  microscope: Microscope,
  atom: Atom,
  dna: Dna,
  palette: Palette,
  image: Image,
  film: Film,
  clapperboard: Clapperboard,
  music: Music,
  speaker: Speaker,
  'volume-2': Volume2,
  mic: Mic,
  radio: Radio,
  video: Video,
  tv: Tv,
  camera: Camera,
  aperture: Aperture,
  feather: Feather,
  paperclip: Paperclip,
  link: Link,
  pin: Pin,
  bookmark: Bookmark,
  'book-open': BookOpen,
  notebook: Notebook,
  newspaper: Newspaper,
  search: Search,
  'message-circle': MessageCircle,
  mail: Mail,
  bell: Bell,
  megaphone: Megaphone,
  phone: Phone,
  'screen-share': ScreenShare,
  'share-2': Share2,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  fingerprint: Fingerprint,
  'log-in': LogIn,
  user: UserRound,
  users: Users,
  crown: Crown,
  trophy: Trophy,
  award: Award,
  gem: Gem,
  diamond: Diamond,
  ghost: Ghost,
  skull: Skull,
  smile: Smile,
  cat: Cat,
  dog: Dog,
  bird: Bird,
  fish: Fish,
  egg: Egg,
  'tree-pine': TreePine,
  leaf: Leaf,
  mountain: Mountain,
  rainbow: Rainbow,
  sun: Sun,
  moon: Moon,
  snowflake: Snowflake,
  'thermometer-sun': ThermometerSun,
  wind: Wind,
  droplet: Droplet,
  umbrella: Umbrella,
  flag: Flag,
  map: Map,
  'map-pin': MapPin,
  compass: Compass,
  anchor: Anchor,
  telescope: Telescope,
  tent: Tent,
  building: Building2,
  'graduation-cap': GraduationCap,
  'hard-hat': HardHat,
  scale: Scale,
  gauge: Gauge,
  activity: Activity,
  'trending-up': TrendingUp,
  'chart-bar': ChartBar,
  calculator: Calculator,
  sigma: Sigma,
  infinity: InfinityIcon,
  'layout-dashboard': LayoutDashboard,
  trello: Trello,
  figma: Figma,
  chrome: Chrome,
  youtube: Youtube,
  joystick: Joystick,
  'gamepad-2': Gamepad2,
  'toy-brick': ToyBrick,
  puzzle: Puzzle,
  swords: Swords,
  target: Target,
  radar: Radar,
  magnet: Magnet,
  bug: Bug,
  hexagon: Hexagon,
  triangle: Triangle,
  square: Square,
  drum: Drum,
  coffee: Coffee,
  utensils: Utensils,
  sofa: Sofa,
  lamp: Lamp,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  gift: Gift,
  tag: Tag,
  wallet: Wallet,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  bitcoin: Bitcoin,
  watch: Watch,
  hourglass: Hourglass,
  timer: Timer,
  calendar: Calendar,
  save: Save,
  settings: Settings,
  'rotate-ccw': RotateCcw,
  shuffle: Shuffle,
  power: Power,
  plug: Plug,
  lightbulb: Lightbulb,
  'life-buoy': LifeBuoy,
  check: Check,
  eye: Eye,
  footprints: Footprints,
  spool: Spool,
};

// Filter out any catalog entries where the lucide-react import resolved to
// `undefined` (e.g. icons renamed/removed in this version of the package).
// Keeps the picker grid free of broken tiles without a per-render runtime
// existence check.
export const PROJECT_ICON_NAMES = Object.keys(PROJECT_ICON_CATALOG).filter(
  (name) => PROJECT_ICON_CATALOG[name] !== undefined
);

export type ProjectColor = {
  id: string;
  label: string;
  className: string;
};

export const PROJECT_COLORS: ProjectColor[] = [
  { id: 'default', label: 'Default', className: 'text-foreground' },
  { id: 'red', label: 'Red', className: 'text-red-500' },
  { id: 'orange', label: 'Orange', className: 'text-orange-500' },
  { id: 'amber', label: 'Amber', className: 'text-amber-500' },
  { id: 'yellow', label: 'Yellow', className: 'text-yellow-500' },
  { id: 'lime', label: 'Lime', className: 'text-lime-500' },
  { id: 'green', label: 'Green', className: 'text-green-500' },
  { id: 'emerald', label: 'Emerald', className: 'text-emerald-500' },
  { id: 'teal', label: 'Teal', className: 'text-teal-500' },
  { id: 'cyan', label: 'Cyan', className: 'text-cyan-500' },
  { id: 'sky', label: 'Sky', className: 'text-sky-500' },
  { id: 'blue', label: 'Blue', className: 'text-blue-500' },
  { id: 'indigo', label: 'Indigo', className: 'text-indigo-500' },
  { id: 'violet', label: 'Violet', className: 'text-violet-500' },
  { id: 'purple', label: 'Purple', className: 'text-purple-500' },
  { id: 'fuchsia', label: 'Fuchsia', className: 'text-fuchsia-500' },
  { id: 'pink', label: 'Pink', className: 'text-pink-500' },
  { id: 'rose', label: 'Rose', className: 'text-rose-500' },
];

export function projectIconColorClass(colorId: string | null | undefined): string {
  if (!colorId) return 'text-foreground';
  return PROJECT_COLORS.find((c) => c.id === colorId)?.className ?? 'text-foreground';
}

/**
 * Project icon value format:
 *   - `lucide:<name>` — render Lucide icon, color applies
 *   - bare `<name>` matching catalog — legacy, treated as `lucide:<name>`
 *   - anything else — render as text (emoji)
 *   - null — default folder icon
 */
export type ParsedProjectIcon =
  | { kind: 'lucide'; name: string; component: LucideIcon }
  | { kind: 'emoji'; char: string }
  | { kind: 'none' };

export function parseProjectIcon(value: string | null | undefined): ParsedProjectIcon {
  if (!value) return { kind: 'none' };
  if (value.startsWith('lucide:')) {
    const name = value.slice('lucide:'.length);
    const component = PROJECT_ICON_CATALOG[name];
    if (component) return { kind: 'lucide', name, component };
    return { kind: 'none' };
  }
  // Bare lucide name (legacy compat)
  const component = PROJECT_ICON_CATALOG[value];
  if (component) return { kind: 'lucide', name: value, component };
  // Treat anything else as emoji
  return { kind: 'emoji', char: value };
}

export function lucideIconValue(name: string): string {
  return `lucide:${name}`;
}

/** @deprecated Use parseProjectIcon. Kept for transitional callers. */
export function getProjectIcon(iconName: string | null | undefined): LucideIcon | null {
  const parsed = parseProjectIcon(iconName);
  return parsed.kind === 'lucide' ? parsed.component : null;
}
